rebuilt mac_osx libs as v2.2.2 with clang instead of gcc
The previous version was v2.2.3+ and built with gcc. This caused

  Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofEPKcmm

on machines without the right version of gcc (https://github.com/microsoft/LightGBM/issues/2460)

This version was rebuilt from tag v2.2.2 using clang and without OpenMP, ie:

  cmake -DUSE_SWIG=ON -DUSE_OPENMP=OFF -DAPPLE_OUTPUT_DYLIB=ON ..

I ran into the following error:

  fatal error: jni_md.h: No such file or directory (Mac OS X)

Which was resolved by using a later version of CMakeLists.txt.
See https://github.com/microsoft/LightGBM/issues/2461